#ifdef OPLUS_FEATURE_MM_FEEDBACK
obj-$(CONFIG_OPLUS_FEATURE_MM_FEEDBACK)	+= multimedia/
#endif /* OPLUS_FEATURE_MM_FEEDBACK */

#ifdef OPLUS_FEATURE_BOOT
obj-y += boot/
#endif /* OPLUS_FEATURE_BOOT */

#ifdef OPLUS_FEATURE_TP_BASIC
obj-$(CONFIG_OPLUS_DEVICE_INFO)  +=  device_info/
#endif /* OPLUS_FEATURE_TP_BASIC */

#ifdef OPLUS_UFS_DRIVER
obj-$(CONFIG_OPLUS_UFS_DRIVER) += storage/common/ufs_oplus_dbg/
#endif

#ifdef OPLUS_FEATURE_DFT
obj-y += dft/
#endif /* OPLUS_FEATURE_DFT */

#ifdef OPLUS_FEATURE_MDMFEATURE
obj-$(CONFIG_OPLUS_FEATURE_MDMFEATURE)     += mdmfeature/
#endif /*OPLUS_FEATURE_MDMFEATURE*/
